# Generated by Django 2.0.6 on 2018-07-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0002_remove_test_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtruefalse',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
