# Generated by Django 2.0.6 on 2018-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0003_auto_20180712_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testabc',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A',
                                   max_length=1),
        ),
    ]
