# Generated by Django 2.0.6 on 2018-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0006_auto_20180712_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtruefalse',
            name='correct_answer',
            field=models.CharField(choices=[('PRAWDA', True), ('FALSZ', False)], max_length=6),
        ),
    ]
