# Generated by Django 2.0.6 on 2018-07-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0007_auto_20180713_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtruefalse',
            name='correct_answer',
            field=models.CharField(choices=[(True, 'PRAWDA'), (False, 'FALSZ')], max_length=6),
        ),
    ]
