# Generated by Django 2.0.6 on 2018-07-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0008_auto_20180713_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtruefalse',
            name='correct_answer',
            field=models.CharField(choices=[('PRAWDA', 'PRAWDA'), ('FALSZ', 'FALSZ')], max_length=6),
        ),
    ]
