# Generated by Django 2.0.6 on 2018-07-18 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0010_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='tests',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
