# Generated by Django 2.0.6 on 2018-07-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tests', '0011_auto_20180718_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('ABC', 'ABC'), ('TF', 'TF'), ('WRITE', 'WRITE'), ('FILLIN', 'FILLIN')],
                                   default='ABC', max_length=6),
            preserve_default=False,
        ),
    ]
